### ISSUE TITLE
 Falla la notificación sonora en Kali

### ISSUE THREAD

**Issue by djmany83** [AnonymousWebHacker/nautax#2]
OS: Kali Linux
Nautax me notifica bien visual, pero no envia la notificacion por sonido.

**Comment by AnonymousWebHacker** [comment]
Nautax notifica los sonidos a travez de `aplay`. Por logica deberis tenerlo nativo en el sistema. Hice una busqueda de paquetes y no hay en los repos , algun paquete que se llame asi `apt search aplay,` asi que tendre que ver , cual es el paquete que se instala, que te instala la utilidad aplay en el sistema

**Comment by AnonymousWebHacker** [comment]
Segun https://packages.ubuntu.com/focal/amd64/alsa-utils/filelist
El paquete responsable de instalar la utilidad `aplay` en el sistema, es `alsa-utils`

Intena solucionar con `sudo apt install alsa-utils`

**Comment by djmany83** [comment]
Listo ahora si Muchas Gracias 👍👍

**Comment by djmany83** [comment]
Problema resuelto en Kali con el sonido de notificacion
